DROP TABLE IF EXISTS public.Contact;
DROP SEQUENCE IF EXISTS public.Contact_id_seq;

DROP TABLE IF EXISTS public.City CASCADE;
DROP SEQUENCE IF EXISTS City_id_seq;

DROP TABLE IF EXISTS public.State CASCADE;
